### ISSUE TITLE
Out of Names?

### ISSUE THREAD

**Issue by bcerjan** [waldoCorp/easy-match#133]
On a whim I was rating names and with the "Traditionally Boys" filter in place, I ran out of names (which I guess I wouldn't have thought was possible...). I ran a `SELECT count(*)...` and I have 655 rated names.

When I turned on "Unusual Names" I started getting names again, which must mean that the default is too restrictive (or I've just rated an abnormally large number of names).

**Comment by williamlief** [comment]
Cool. I’ll start working on the long neglected issue #4

**Comment by williamlief** [comment]
Fixed in 7ee2139
