### ISSUE TITLE
Remove popularity filter when letter filters are applied

### ISSUE THREAD

**Issue by williamlief** [waldoCorp/easy-match#135]
When a user starts using the letter filters the name space shrinks dramatically under the current default popularity filter. I think we should remove the default popularity filter whenever the user starts using other filters (except gender?)

Labelled as a bug because code is executing as intended, but we didn't really think through the impacts of the filter layering.

**Comment by bcerjan** [comment]
I agree with leaving the traditionally-gendered toggle fixed while removing the other choices. Note that "default" popularity is still fairly popular (see issue #4), but on this page this is an easy fix.
