### ISSUE TITLE
Add filter and sort to my names

### ISSUE THREAD

**Issue by williamlief** [waldoCorp/easy-match#137]
User would like to separate yes / no names, should also add an alphabetical sort

**Comment by williamlief** [comment]
Can we also add this to my matches?

**Comment by bcerjan** [comment]
Can't see why not, sure.

**Comment by bcerjan** [comment]
I've done this now in `ben_test` but I'm not sure how pretty it is. It's particularly hard to use for mobile users (I assume), but let me know what you think / how it can be improved @williamlief.

**Comment by williamlief** [comment]
Looks great on desktop.
